import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
fs.mkdirSync('test-results',{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:844,height:390},hasTouch:true});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const url=process.env.BASE_URL||'http://127.0.0.1:8123/huroner-platformer/dist/?qa=1';
const state=()=>page.evaluate(()=>window.__ferretQA.state());
const center=async selector=>{const r=await page.locator(selector).boundingBox();return {x:r.x+r.width/2,y:r.y+r.height/2};};
const cdp=await page.context().newCDPSession(page);
await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});
const touch=(type,touchPoints)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints});
try {
    await page.goto(url);await page.waitForFunction(()=>window.__ferretQA);
    await page.click('#start');await page.click('[data-level="0"]');
    await page.waitForFunction(()=>window.__ferretQA.state().player.grounded);
    const first=await state();assert.equal(first.player.bodyHeight,42);
    const origin={...await center('#swipe-zone'),id:1};
    await touch('touchStart',[origin]);
    await touch('touchMove',[{...origin,y:origin.y+46}]);
    await page.waitForTimeout(90);
    let s=await state();assert(s.player.crouched && s.player.bodyHeight===24);
    assert(Math.abs(s.player.feet-first.player.feet)<2,'feet must stay on floor');
    await page.screenshot({path:'test-results/crouch-swipe.png'});
    // A sideways drag takes priority when it becomes the dominant direction.
    await touch('touchMove',[{...origin,x:origin.x+65,y:origin.y+46}]);
    await page.waitForTimeout(200);
    s=await state();assert(!s.player.crouched && s.player.vx>0);
    await touch('touchEnd',[]);
    await page.keyboard.down('ArrowDown');await page.waitForTimeout(80);
    assert((await state()).player.crouched,'keyboard crouch');
    const start=(await state()).player.x;
    await page.keyboard.down('ArrowRight');await page.waitForTimeout(220);
    s=await state();assert(s.player.x>start && s.player.vx<=86,'slow crawl');
    await page.keyboard.up('ArrowRight');
    // Model a future hidden low passage: releasing down cannot expand through its roof.
    await page.evaluate(()=>{const q=window.__ferretQA;const b=q.scene.player.body;q.scene.level.solids.push({x:b.left-5,y:b.bottom-38,width:40,height:10,surface:'stone'});});
    await page.keyboard.up('ArrowDown');await page.waitForTimeout(100);
    assert((await state()).player.crouched,'cannot stand inside low ceiling');
    await page.evaluate(()=>window.__ferretQA.scene.level.solids.pop());
    await page.waitForTimeout(100);
    assert(!(await state()).player.crouched,'stands once clear');
    await page.keyboard.down('s');await page.keyboard.down('Space');await page.waitForTimeout(100);
    assert((await state()).player.crouched && (await state()).player.vy>=0,'crouch suppresses jump');
    await page.keyboard.up('Space');await page.keyboard.up('s');
    await page.mouse.wheel(0,70);await page.waitForTimeout(50);
    assert((await state()).player.crouched,'mouse wheel down');
    await page.mouse.wheel(0,-70);await page.waitForTimeout(50);
    assert(!(await state()).player.crouched,'mouse wheel up');
    await page.click('#pause');assert(!(await state()).player.crouched,'release works at pause');
    await page.click('#resume');
    await page.evaluate(()=>localStorage.setItem('ferret-jump-controls-v1','buttons'));
    await page.goto(url);await page.waitForFunction(()=>window.__ferretQA);
    await page.click('#start');await page.click('[data-level="0"]');
    await page.waitForFunction(()=>window.__ferretQA.state().player.grounded);
    assert(await page.locator('[data-control="crouch"]').isVisible());
    const button={...await center('[data-control="crouch"]'),id:2};
    await touch('touchStart',[button]);await page.waitForTimeout(90);
    assert((await state()).player.crouched,'button crouch');
    await touch('touchEnd',[]);await page.waitForTimeout(90);
    assert(!(await state()).player.crouched,'button release');
    assert.deepEqual(errors,[]);
    console.log('PASS: vertical swipe, keyboard and button crouch, slow crawl, feet, low roof and release.');
} finally {await browser.close();}
