const {chromium,webkit}=require('playwright');const fs=require('node:fs');const OUT=process.env.QA_OUTPUT||'/tmp/huroner-world-qa';fs.mkdirSync(OUT,{recursive:true});const assert=require('node:assert/strict');
(async()=>{const results=[];for(const [name,type] of [['chromium',chromium],['webkit',webkit]]){
 const browser=await type.launch({executablePath:name==='chromium'?process.env.CHROMIUM_EXECUTABLE:undefined});
 const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2,hasTouch:true,isMobile:true,ignoreHTTPSErrors:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
 const base=process.env.QA_BASE_URL||'http://127.0.0.1:8000/huroner-survivor/';await page.goto(base);await page.locator('#start').click();await page.locator('#pause').click();await page.evaluate(()=>document.querySelector('#pause-screen').hidden=true);
 const result=await page.evaluate(async base=>{
  const {createRenderer}=await import(base+'render.js');const {Game}=await import(base+'core.js');const {worldStage}=await import(base+'world.js');
  const canvas=document.createElement('canvas');document.querySelector('#game-shell').append(canvas);canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;z-index:1';const renderer=createRenderer({canvas});const game=new Game(()=>.5);game.enemies=[];game.gems=[{x:40,y:40,value:2}];game.pickups=[{x:-50,y:30,type:'meat'}];const enemy=game.spawn('rabbit');Object.assign(enemy,{x:75,y:-80,speed:0,specialAttack:{kind:'rabbit',x:60,y:80,radius:35,phase:'warning'}});
  window.qaScene={game,renderer,canvas};const signature=()=>{const c=document.createElement('canvas');c.width=c.height=32;c.getContext('2d').drawImage(canvas,0,0,32,32);return c.toDataURL()};
  const render=(level,time,reducedMotion=false)=>{game.level=level;game.time=time;const before=JSON.stringify(game);renderer.draw(game,{reducedMotion});if(JSON.stringify(game)!==before)throw Error('Renderer mutated Game');return signature()};
  const baseImage=render(1,10),same=render(4,10);if(baseImage!==same)throw Error('Changed before threshold');const first=render(5,10);if(first!==same)throw Error('Abrupt transition');const middle=render(5,10.9);if(middle===first)throw Error('No crossfade');const frozen=render(5,10.9);if(frozen!==middle)throw Error('Transition advances while paused');const complete=render(5,12);if(complete===first||complete===middle)throw Error('Transition did not finish');
  const images=[];for(const level of [5,10,15,20,25,30,35])images.push(render(level,20,true));if(new Set(images).size!==images.length)throw Error('Missing world step');const reset=render(1,10,false);if(reset!==baseImage)throw Error('World did not reset');
  const boundaries=[1,4,5,9,10,14,15,19,20,24,25,29,30].map(n=>[n,worldStage(n)]);return {boundaries,checks:['thresholds','same appearance within stage','crossfade','pause freezes transition','all steps visually distinct through level35','reset','reduced motion instant','renderer does not mutate simulation']};
 },base);
 assert.deepEqual(result.boundaries.map(x=>x[1]),[0,0,1,1,2,2,3,3,4,4,5,5,6]);
 for(const level of [1,5,10,15,20,25]){await page.evaluate(level=>{const {game,renderer}=qaScene;game.level=level;renderer.draw(game,{reducedMotion:true})},level);await page.screenshot({path:OUT+`/world-${name}-${level}.png`});}
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>{qaScene.renderer.resize();qaScene.renderer.draw(qaScene.game,{reducedMotion:true})});await page.screenshot({path:OUT+`/world-${name}-desktop.png`});assert.deepEqual(errors,[]);results.push({browser:name,version:browser.version(),...result,errors,result:'PASS'});await browser.close();
 }fs.writeFileSync(OUT+'/'+(process.env.QA_BASE_URL?'world-public':'world-local')+'.json',JSON.stringify({date:new Date().toISOString(),results},null,2));console.log(JSON.stringify(results.map(x=>({browser:x.browser,result:x.result,checks:x.checks}))));})().catch(e=>{console.error(e);process.exit(1)});
