delete process.env.PLAYWRIGHT_BROWSERS_PATH;
const {chromium,webkit}=require('playwright');
const fs=require('node:fs');
const assert=require('node:assert/strict');
const OUT=process.env.QA_OUTPUT || '/tmp/huroner-v2-qa';
fs.mkdirSync(OUT,{recursive:true});
const BASE=process.env.QA_BASE_URL || 'http://127.0.0.1:8000/huroner-survivor-2/';
const results=[];
const wait=page=>page.waitForTimeout(150);
async function run(name,type,mobile){
 const browser=await type.launch({headless:true,executablePath:type===chromium?process.env.CHROMIUM_EXECUTABLE:undefined,args:type===chromium?['--no-sandbox']:[]});
 const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},deviceScaleFactor:mobile?3:1,isMobile:mobile,hasTouch:mobile,locale:'es-ES'});
 const page=await context.newPage(); const errors=[],failed=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)failed.push(`${r.status()} ${r.url()}`)});page.on('requestfailed',r=>failed.push(r.url()+': '+r.failure()?.errorText));
 await page.route('**/huroner-survivor-2/app.js',async route=>{const r=await route.fetch();await route.fulfill({response:r,body:(await r.text()).replace('const game = new Game();','const game = window.__qaGame = new Game();')});});
 const entry={name,browser:browser.version(),viewport:mobile?'390x844 DPR3 (canvas capped2)':'1440x1000 DPR1',checks:[],errors,failed};results.push(entry);
 const check=async(label,fn)=>{try{await fn();entry.checks.push({label,result:'PASS'});console.log(name,label,'PASS')}catch(e){entry.checks.push({label,result:'FAIL',error:e.stack});console.log(name,label,'FAIL',e.message);await page.screenshot({path:`${OUT}/${name}-failure-${entry.checks.length}.png`}).catch(()=>{});throw e;}};
 const shot=async suffix=>page.screenshot({path:`${OUT}/${name}-${suffix}.png`});
 try{
 await page.goto(BASE);await page.waitForFunction(()=>window.__qaGame);await wait(page);
 await check('boot, Spanish menu, artwork, controls ≥44px',async()=>{assert.equal(await page.locator('html').getAttribute('lang'),'es');assert.equal(await page.locator('#home').isVisible(),true);assert.equal(await page.locator('.hero-illustration img').evaluate(e=>e.complete&&e.naturalWidth>0),true);for(const id of ['start','config','language','sound']){const b=await page.locator('#'+id).boundingBox();assert.ok(b.height>=44&&b.width>=44,id);}await shot('menu-es');});
 await check('ES/EN and independent persisted preferences',async()=>{await page.evaluate(()=>{localStorage.setItem('huroner-language','es');localStorage.setItem('huroner-record','{"time":42,"kills":7}');});await page.locator('#language').click();assert.equal(await page.locator('html').getAttribute('lang'),'en');await shot('menu-en');await page.locator('#config').click();await page.locator('#attack-manual').click();await page.locator('#attack-left').click();await page.locator('#settings-sound').click();await shot('settings');await page.locator('#settings-done').click();await page.reload();await page.waitForFunction(()=>window.__qaGame);assert.equal(await page.locator('html').getAttribute('lang'),'en');const prefs=await page.evaluate(()=>JSON.parse(localStorage.getItem('huroner-survivor-2:preferences:v1')));assert.deepEqual(prefs,{language:'en',muted:true,attackMode:'button',attackSide:'left'});assert.equal(await page.evaluate(()=>localStorage.getItem('huroner-record')),'{"time":42,"kills":7}');await page.locator('#start').click();assert.equal(await page.locator('#attack-button').evaluate(e=>e.classList.contains('left')),true);});
 await check('manual nearest attack and keyboard movement',async()=>{await page.evaluate(()=>{const g=window.__qaGame;g.enemies=[];g.spawnTimer=999;g.pickupTimer=999;g.player.invuln=10;const e=g.spawn('rabbit');Object.assign(e,{x:g.player.x+55,y:g.player.y,hp:1000,maxHp:1000,speed:0});});const before=await page.evaluate(()=>({hp:__qaGame.enemies[0].hp,x:__qaGame.player.x}));await page.locator('#attack-button').click();assert.ok(await page.evaluate(()=>__qaGame.enemies[0].hp)<before.hp);await page.keyboard.down('d');await page.waitForTimeout(160);await page.keyboard.up('d');assert.ok(await page.evaluate(()=>__qaGame.player.x)>before.x+4);assert.equal(await page.locator('#game-shell').evaluate(e=>getComputedStyle(e).touchAction),'none');});
 await check('pause freezes time buffs cooldown; resume resets held keyboard',async()=>{await page.evaluate(()=>{__qaGame.speedBoostTimer=10;__qaGame.fireTimer=8});await page.keyboard.down('w');await page.keyboard.press('Escape');await wait(page);const before=await page.evaluate(()=>JSON.stringify([__qaGame.time,__qaGame.player.x,__qaGame.player.y,__qaGame.speedBoostTimer,__qaGame.fireTimer,__qaGame.manualAttackCooldown]));await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>JSON.stringify([__qaGame.time,__qaGame.player.x,__qaGame.player.y,__qaGame.speedBoostTimer,__qaGame.fireTimer,__qaGame.manualAttackCooldown])),before);await shot('pause');await page.locator('#resume').click();const pos=await page.evaluate(()=>__qaGame.player.y);await wait(page);assert.equal(await page.evaluate(()=>__qaGame.player.y),pos);await page.keyboard.up('w');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await wait(page);assert.equal(await page.locator('#pause-screen').isVisible(),true);await page.locator('#resume').click();});
 if(mobile&&type===chromium)await check('real Chromium two-touch move+attack and touchCancel reset',async()=>{const client=await context.newCDPSession(page);const attack=await page.locator('#attack-button').boundingBox();const x=attack.x+attack.width/2,y=attack.y+attack.height/2;const initial=await page.evaluate(()=>({x:__qaGame.player.x,hp:__qaGame.enemies[0].hp}));await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:280,y:650,id:1}]});await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:325,y:650,id:1}]});await page.waitForTimeout(100);await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:325,y:650,id:1},{x,y,id:2}]});await page.waitForTimeout(100);assert.ok(await page.evaluate(()=>__qaGame.player.x)>initial.x+5);assert.ok(await page.evaluate(()=>__qaGame.enemies[0].hp)<initial.hp);assert.equal(await page.locator('#attack-button').evaluate(e=>e.classList.contains('pressed')),true);await client.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});const end=await page.evaluate(()=>__qaGame.player.x);await wait(page);assert.equal(await page.evaluate(()=>__qaGame.player.x),end);assert.equal(await page.locator('#joystick').isVisible(),false);assert.equal(await page.locator('#attack-button').evaluate(e=>e.classList.contains('pressed')),false);await client.detach();});
 await check('captured drag release and lostpointercapture reset',async()=>{const shell=await page.locator('#game-shell').boundingBox();await page.mouse.move(shell.x+shell.width*.7,shell.y+shell.height*.7);await page.mouse.down();await page.mouse.move(shell.x+shell.width*.7+30,shell.y+shell.height*.7);await wait(page);await page.evaluate(()=>document.querySelector('#game-shell').dispatchEvent(new PointerEvent('lostpointercapture',{pointerId:1,bubbles:true})));const x=await page.evaluate(()=>__qaGame.player.x);await wait(page);assert.equal(await page.evaluate(()=>__qaGame.player.x),x);assert.equal(await page.locator('#joystick').isVisible(),false);await page.mouse.up();});
 await check('level-up freezes, carries XP, rejects stale/double choice',async()=>{await page.evaluate(()=>{const g=__qaGame;g.xp=30;g.checkLevel()});await page.locator('#choices button').first().waitFor();const time=await page.evaluate(()=>__qaGame.time);await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>__qaGame.time),time);await shot('choice');await page.evaluate(()=>{const b=document.querySelector('#choices button');b.click();b.click();document.querySelector('#choices button')?.dispatchEvent(new MouseEvent('click',{bubbles:true,detail:2}));});assert.equal(await page.evaluate(()=>Object.values(__qaGame.upgrades).reduce((a,b)=>a+b,0)),1);assert.equal(await page.evaluate(()=>__qaGame.state),'levelup');await page.locator('#choices button').first().click();while(await page.locator('#level-screen').isVisible())await page.locator('#choices button').first().click();assert.equal(await page.evaluate(()=>__qaGame.state),'playing');});
 await check('populated arena, species, warnings, pickups, boss IDs',async()=>{await page.evaluate(()=>{const g=__qaGame;g.enemies=[];g.effects=[];g.gems=[];g.pickups=[];g.player.x=g.player.y=0;g.player.invuln=999;g.time=120;g.level=11;g.mutate();g.speedBoostTimer=20;g.fireTimer=15;['rabbit','hare','quail','chicken'].forEach((kind,i)=>{const e=g.spawn(kind);Object.assign(e,{x:(i%2?1:-1)*95,y:(i<2?-115:105),speed:0,ability:999});});const a=g.enemies[0];a.specialAttack={kind:'rabbit',phase:'warning',x:-20,y:-120,radius:30,time:999,duration:.34,startX:a.x,startY:a.y};const b=g.enemies[2];b.specialAttack={kind:'quail',phase:'warning',x:b.x,y:b.y,angle:-Math.PI/2,count:5,time:999};for(let i=0;i<28;i++)g.gems.push({x:Math.cos(i*2.4)*(70+i*3),y:Math.sin(i*2.4)*(70+i*3),value:i%5?2:8});g.gems.push({x:80,y:0,value:15,heal:true});['meat','oil','fire'].forEach((type,i)=>Object.assign(g.spawnPickup(type),{x:-95+i*65,y:200}));const boss=g.spawn('chicken',true,10);Object.assign(boss,{x:130,y:-220,speed:0,ability:999});const boss2=g.spawn('hare',true,5);Object.assign(boss2,{x:-150,y:260,speed:0,ability:999});});await wait(page);assert.equal(await page.locator('#boss-count').textContent(),'2 GUARDIANS');const selected=await page.locator('#boss-hud').getAttribute('data-boss-id');assert.ok(await page.evaluate(id=>__qaGame.enemies.some(e=>String(e.id)===id&&e.boss),selected));await shot('arena');});
 await check('death, retry clean state, victory final boss, record',async()=>{await page.evaluate(()=>{__qaGame.player.invuln=0;__qaGame.hurt(1e6)});await page.locator('#end-screen').waitFor();assert.equal(await page.locator('#end-title').textContent(),'The meadow remembers you');await shot('death');await page.locator('#retry').click();const reset=await page.evaluate(()=>({level:__qaGame.level,hp:__qaGame.player.hp,upgrades:__qaGame.upgrades,buffs:[__qaGame.fireTimer,__qaGame.speedBoostTimer]}));assert.deepEqual(reset,{level:1,hp:100,upgrades:{},buffs:[0,0]});await page.evaluate(()=>{const g=__qaGame;g.time=599.99;g.player.invuln=999;g.step(.02);g.hit(g.boss,1e9)});await page.locator('#end-screen').waitFor();assert.equal(await page.locator('#end-title').textContent(),'The last clearing is yours');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('huroner-survivor-2:record:v1')).won),true);await shot('victory');await page.locator('#back').click();});
 await check('auto mode attacks through shared gate; sound toggle and resize',async()=>{await page.locator('#config').click();await page.locator('#attack-auto').click();await page.locator('#settings-sound').click();await page.locator('#settings-done').click();await page.locator('#start').click();assert.equal(await page.locator('#attack-button').isVisible(),false);await page.evaluate(()=>{const g=__qaGame;g.spawnTimer=999;g.enemies=[];g.player.invuln=999;const e=g.spawn('rabbit');Object.assign(e,{x:g.player.x+60,y:g.player.y,hp:1000,maxHp:1000,speed:0});});await page.waitForTimeout(650);const hp=await page.evaluate(()=>__qaGame.enemies[0].hp);assert.ok(hp<=960&&hp>=940,`auto hp ${hp}`);if(mobile){await page.setViewportSize({width:844,height:390});await wait(page);assert.ok((await page.locator('#pause').boundingBox()).y>=0);await shot('landscape');await page.setViewportSize({width:320,height:568});await page.locator('#pause').click();await page.locator('#quit').click();await page.locator('#config').click();const layout=await page.locator('.settings-panel').evaluate(e=>({top:e.getBoundingClientRect().top,bottom:e.getBoundingClientRect().bottom,scroll:document.querySelector('#settings-screen').scrollHeight,client:document.querySelector('#settings-screen').clientHeight}));assert.ok(layout.top>=0,JSON.stringify(layout));await shot('small-settings');}});
 await check('loaded-frame performance and bounded entities',async()=>{await page.reload();await page.waitForFunction(()=>window.__qaGame);await page.locator('#start').click();await page.evaluate(()=>{const g=__qaGame;g.player.invuln=999;g.spawnTimer=999;g.enemies=[];for(let i=0;i<170;i++){const e=g.spawn(['rabbit','hare','quail','chicken'][i%4]);Object.assign(e,{x:Math.cos(i)* (120+i%10*18),y:Math.sin(i)*(120+i%10*18),hp:1e6,maxHp:1e6,ability:999});}for(let i=0;i<350;i++)g.gems.push({x:Math.cos(i)*250,y:Math.sin(i)*250,value:2});});entry.performance=await page.evaluate(()=>new Promise(resolve=>{const gaps=[];let last=performance.now();const start=last;function tick(now){gaps.push(now-last);last=now;if(now-start<3000)requestAnimationFrame(tick);else{gaps.sort((a,b)=>a-b);resolve({durationMs:now-start,frames:gaps.length,meanMs:gaps.reduce((a,b)=>a+b,0)/gaps.length,p95Ms:gaps[Math.floor(gaps.length*.95)],enemies:__qaGame.enemies.length,gems:__qaGame.gems.length,dpr:devicePixelRatio})}}requestAnimationFrame(tick)}));assert.ok(entry.performance.enemies<=170);await shot('stress');});
 await check('no blocking console/network errors',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(failed,[])});
 }catch(e){entry.fatal=e.message;}finally{await context.close();await browser.close();fs.writeFileSync(`${OUT}/browser-results.json`,JSON.stringify(results,null,2));}
}
(async()=>{for(const [name,type,mobile] of [['chromium-mobile',chromium,true],['chromium-desktop',chromium,false],['webkit-mobile',webkit,true],['webkit-desktop',webkit,false]]){if(process.argv[2]&&!name.startsWith(process.argv[2]))continue;await run(name,type,mobile);}console.log(JSON.stringify(results.map(r=>({name:r.name,fatal:r.fatal,passed:r.checks.filter(c=>c.result==='PASS').length,performance:r.performance})),null,2));if(results.some(r=>r.fatal))process.exitCode=1;})();
